### ISSUE TITLE
Write a beautiful README

### ISSUE THREAD

**Issue by BenEmdon** [klipfolio-decode/BackEnd#44]
# TODO:
* Description
* Technology stack
* Contributing
* Slack link

**Comment by gneius** [comment]
👍  On top of beautiful it should also be informative :)
An overview of the architecture would also be good. 
You can also link to travis #34 etc once you have those.

**Comment by richardison** [comment]
https://travis-ci.org/klipfolio-decode/BackEnd 😄

**Comment by gneius** [comment]
Cool, now you can add this shield to your README.

https://travis-ci.org/klipfolio-decode/BackEnd.svg?branch=master

**Comment by BenEmdon** [comment]
@gneius Thanks!

**Comment by BenEmdon** [comment]
Readme is as beautiful as it will get
+ this project is stale

**Comment by gneius** [comment]
@BenEmdon what's up :)

**Comment by BenEmdon** [comment]
Hey @gneius hows it going 👋 
I was just closing some issues on some stale projects of mine 😅
